auth0:
  audience: https://aquaponics/
  domain: dev-2vbk0k7f01uni0gc.us.auth0.com
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-2vbk0k7f01uni0gc.us.auth0.com/